name: lint

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get install tesseract-ocr
          python -m pip install --upgrade pip
          pip install seed-isort-config isort black flake8
          pip install -r requirements.txt
      - name: Lint with isort, black and flake8
        run: |
          seed-isort-config
          isort **/*.py -c -v
          black --check document_scanner/ test_script.py
          flake8 document_scanner/ test_script.py
